name: Manual Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag (e.g., v1.2.3)'
        required: true
        type: string
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set build number from GitHub run number
        id: build
        run: |
          echo "build_number=${GITHUB_RUN_NUMBER}" >> "$GITHUB_OUTPUT"

      - name: Build with Maven
        run: |
          mvn clean package \
            -DgitTag=${{ github.event.inputs.tag }} \
            -DbuildNumber=${{ steps.build.outputs.build_number }}

      - name: Create zip archive with JAR
        run: |
          cd target
          zip json-http-excel-guava.zip json-http-excel-guava.jar

      - name: Create GitHub Release (if it doesn't exist)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: Release ${{ github.event.inputs.tag }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: target/json-http-excel-guava.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
